package.path = GetScriptsDir() .. "MKW/MKW_core.lua"
local core = require("MKW_core")

function onScriptStart()
	MsgBox("Script Started.")
end

function onScriptCancel()
	MsgBox("Script Ended.")
end

function onScriptUpdate()
	if core.getVehicle() == "Mach Bike" or core.getVehicle() == "Zip Zip" or core.getVehicle() == "Sugarscoot" or core.getVehicle() == "Flame Runner" then
		if core.getFrameOfInput() <= 13 + 3 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 14 + 3 then SetMainStickX(59) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 27 + 3 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 34 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 36 + 3 then SetMainStickX(170) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 37 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 38 + 3 then SetMainStickX(161) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 40 + 3 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 41 + 3 then SetMainStickX(197) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 42 + 3 then SetMainStickX(179) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 43 + 3 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 45 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 46 + 3 then SetMainStickX(179) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 47 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 48 + 3 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 49 + 3 then SetMainStickX(197) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 50 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 51 + 3 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 52 + 3 then SetMainStickX(188) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 53 + 3 then SetMainStickX(197) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 55 + 3 then SetMainStickX(179) SetMainStickY(128) PressButton("A") 
		elseif core.getFrameOfInput() <= 59 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A") 
		elseif core.getFrameOfInput() <= 64 + 3 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 65 + 3 then SetMainStickX(205) SetMainStickY(112) PressButton("A")
		elseif core.getFrameOfInput() <= 80 + 3 then SetMainStickX(104) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 83 + 3 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 84 + 3 then SetMainStickX(68) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 86 + 3 then SetMainStickX(68) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 91 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 92 + 3 then SetMainStickX(188) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 93 + 3 then SetMainStickX(205) SetMainStickY(112) PressButton("A")
		elseif core.getFrameOfInput() == 94 + 3 then SetMainStickX(128) SetMainStickY(112) PressButton("A")
		elseif core.getFrameOfInput() == 95 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 96 + 3 then SetMainStickX(205) SetMainStickY(112) PressButton("A")
		elseif core.getFrameOfInput() == 97 + 3 then SetMainStickX(197) SetMainStickY(112) PressButton("A")
		elseif core.getFrameOfInput() == 98 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 99 + 3 then SetMainStickX(188) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 104 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 105 + 3 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() == 106 + 3 then SetMainStickX(59) SetMainStickY(128) PressButton("D-Up")
		elseif core.getFrameOfInput() <= 127 + 3 then SetMainStickX(59) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 139 + 3 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 141 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 143 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 144 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 146 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 147 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 149 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 151 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 153 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 154 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 156 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 157 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 158 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 159 + 3 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 161 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 163 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 164 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 166 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 167 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 169 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 171 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 173 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 174 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 176 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 177 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 179 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 181 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 183 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 184 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 186 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 187 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 189 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 191 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 193 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 194 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 196 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 197 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 199 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 201 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 203 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 204 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 206 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 207 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 209 + 3 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 210 + 3 then SetMainStickX(205) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 232 + 3 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() < 240 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		else CancelScript()
		end
	end
	
	if core.getVehicle() == "Shooting Star" or core.getVehicle() == "Magikruiser" or core.getVehicle() == "Quacker" or core.getVehicle() == "Dolphin Dasher" or core.getVehicle() == "Standard Bike S" or core.getVehicle() == "Standard Bike M" or core.getVehicle() == "Standard Bike L"  or core.getVehicle() == "Bullet Bike" or core.getVehicle() == "Bit Bike" then
		if core.getFrameOfInput() <= 12 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 13 then SetMainStickX(205) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 32 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 33 then SetMainStickX(205) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 83 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 84 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 85 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 86 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 88 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 90 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 92 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 93 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 95 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 96 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 98 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 100 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 102 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 103 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 105 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 106 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 108 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 110 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 112 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 113 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 115 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 116 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 118 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 120 then SetMainStickX(205) SetMainStickY(128) 
		elseif core.getFrameOfInput() <= 122 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 123 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 125 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 126 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 128 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 130 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 132 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 133 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 135 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 136 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() == 137 then SetMainStickX(152) SetMainStickY(128)
		elseif core.getFrameOfInput() == 138 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 140 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 142 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 143 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 145 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 146 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 148 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 150 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 152 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 153 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 155 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 156 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 158 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 160 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 162 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 163 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 165 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 166 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 168 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 170 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 172 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 173 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 175 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 176 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 178 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 180 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 182 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 183 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 185 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 186 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 188 then SetMainStickX(152) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 189 then SetMainStickX(205) SetMainStickY(128) PressButton("A") PressButton("D-Up") 
		elseif core.getFrameOfInput() <= 193 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 226 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 232 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() < 240 then SetMainStickX(205) SetMainStickY(205) PressButton("A")
		else CancelScript()
		end
	end
	
	if core.getVehicle() == "Sneakster" or core.getVehicle() == "Spear" or core.getVehicle() == "Phantom" or core.getVehicle() == "Jet Bubble" or core.getVehicle() == "Wario Bike" then
		if core.getFrameOfInput() <= 18 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 19 then SetMainStickX(205) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 22 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 23 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 26 then SetMainStickX(205) SetMainStickY(104) PressButton("A")
		elseif core.getFrameOfInput() <= 39 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 41 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 43 then SetMainStickX(128) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 45 then SetMainStickX(205) SetMainStickY(205)
		elseif core.getFrameOfInput() <= 50 then SetMainStickX(205) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() <= 52 then SetMainStickX(128) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() == 53 then SetMainStickX(205) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() <= 60 then SetMainStickX(128) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() <= 76 then SetMainStickX(59) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() == 77 then SetMainStickX(205) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 92 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 96 then SetMainStickX(205) SetMainStickY(128)
		elseif core.getFrameOfInput() == 97 then SetMainStickX(59) SetMainStickY(128) PressButton("D-Up")
		elseif core.getFrameOfInput() <= 116 then SetMainStickX(59) SetMainStickY(128)
		elseif core.getFrameOfInput() == 117 then SetMainStickX(128) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 122 then SetMainStickX(205) SetMainStickY(205)
		elseif core.getFrameOfInput() <= 127 then SetMainStickX(205) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() <= 129 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 132 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 134 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 137 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 139 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 141 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 147 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 163 then SetMainStickX(59) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() == 164 then SetMainStickX(59) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 183 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 184 then SetMainStickX(128) SetMainStickY(128) PressButton("A") PressButton("D-Up")
		elseif core.getFrameOfInput() <= 199 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 202 then SetMainStickX(59) SetMainStickY(128)
		elseif core.getFrameOfInput() <= 207 then SetMainStickX(59) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 213 then SetMainStickX(205) SetMainStickY(205) PressButton("A")
		elseif core.getFrameOfInput() <= 221 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 225 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 226 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 228 then SetMainStickX(128) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() <= 231 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		elseif core.getFrameOfInput() == 232 then SetMainStickX(128) SetMainStickY(104) PressButton("A")
		elseif core.getFrameOfInput() < 240 then SetMainStickX(205) SetMainStickY(128) PressButton("A")
		else CancelScript()
		end
	end
end

function onStateLoaded()

end

function onStateSaved()

end
